### ISSUE TITLE
Transfer the project to GitHub collective organization?

### ISSUE THREAD

**Issue by gforcada** [nazrulworld/collective.recipe.vscode#24]
Hi @nazrulworld 👋🏾 

Given that you are already a member of https://github.com/collective would you be ok with transferring this project there? 🤞🏾 

With GitHub being owned by Microsoft and VSCode being developed by them, we keep seeing more and more integration of the two.

Moreover a quick glance at Plone developers preferred code editor shows that VSCode is gaining more and more popularity 🚀 

It would be great if we have it there so more collaboration can happen 😄

**Comment by nazrulworld** [comment]
@gforcada that is fantastic idea. I don't have any problem at all to transfer.

**Comment by datakurre** [comment]
@gforcada What is the known good set of usernames at PyPI, who should have release rights? Assuming that @nazrulworld would also like to pass release right to the community?

**Comment by nazrulworld** [comment]
Yes, that would be the realistic idea for publishing to PyPi. I will need username.

**Comment by gforcada** [comment]
For collective users we have a `collective` user, which some community members have access to, that would be the safest.

Recently on PyPI they created organization profiles, we have one such for Plone, but AFAIK there is no such organization at PyPI for `collective`. It would be a good idea, actually even more than for Plone, so we can eventually get _all_ collective packages under an organization and whoever manages that organization can make releases of all packages.

If on top of that you add me (`gilforcada`) that would be a good idea as well. But I expect that you can keep doing the releases nonetheless, right? 😄

**Comment by nazrulworld** [comment]
Yes, I can keep doing the releases, but also I have invited you @gforcada already :)

**Comment by gforcada** [comment]
Thanks, I already accepted the invitation 😄
